class KintypType7Anime extends KinTypBase{get main_color(){return this.getAttribute("main_color")||"#ffffff"}static get observedAttributes(){var a=super.observedAttributes;return a.push("main_color"),a}attributeChangedCallback(a,b,c){super.attributeChangedCallback(a,b,c),"main_color"===a&&null!=b&&(document.getElementById("obj_translate_right_f7_e"+this.id).style.borderBottomColor=c)}constructor(){super();for(var a,b=this.getElementsByClassName("kintyp-left"),c=``;0<b.length;){var d=this.getNode(b[0]);a=d.getAttribute("data-id"),a=a?" data-id=\""+a+"\"":"",d.classList.remove("kintyp-left"),c=c+`<div class="`+d.className+` kintyp-left-f7-e`+this.id+` t_padding_right" style="position: relative; white-space:nowrap;`+d.style.cssText+`"`+a+`>`+d.innerHTML+`</div>`,this.removeChild(d)}for(var e=this.getElementsByClassName("kintyp-right"),f=``;0<e.length;){var g=this.getNode(e[0]);a=g.getAttribute("data-id"),a=a?" data-id=\""+a+"\"":"",g.classList.remove("kintyp-right"),f=f+`<div class="`+g.className+` kintyp-right-f7-e`+this.id+` pr_3_0 pb_0_5" style="position: relative; white-space:nowrap;`+g.style.cssText+`"`+a+`>`+g.innerHTML+`</div>`,this.removeChild(g)}var h=document.createElement("template");h.innerHTML=`
      `+this.back_panel+`

        <div id="obj_texts_f7_e`+this.id+`" class="kintyp_flex_left_r" style="align-items: flex-end;">

          <div id="obj_rotate_left_f7_e`+this.id+`" style="transform-origin: 100% 100%; overflow: hidden; position: relative;">
              <div id="obj_left_f7_e`+this.id+`" class="kintyp_flex_left_c mt_1_0"  style="transform-origin: 100% 100%; overflow: hidden; position: relative;">`+c+`
              </div>
          </div>
          <div id="obj_border_right_f7_e`+this.id+`" style="overflow: hidden; position: relative;">
              <div id="obj_translate_right_f7_e`+this.id+`" style="overflow: hidden; position: relative; border-bottom-style: solid; border-bottom-color: `+this.main_color+`" class="bb_0_5">
                  <div id="obj_right_f7_e`+this.id+`" class="kintyp_flex_left_c"  style="overflow: hidden; position: relative;">`+f+`
                  </div>
              </div>
          </div>
          
        </div>`,this.finishConstruction(h)}handleResize(){this.setSizes();for(var a=0,b=0,c=0,d=0,e=document.getElementsByClassName("kintyp-left-f7-e"+this.id),f=0;f<e.length;f++){var g=e[f],j=g.offsetWidth,k=g.offsetHeight;j>c&&(c=j),d+=k}for(var l=document.getElementsByClassName("kintyp-right-f7-e"+this.id),f=0;f<l.length;f++){var m=l[f],j=m.getBoundingClientRect().width,k=m.getBoundingClientRect().height;j>a&&(a=j),b+=k}var n=document.getElementById("obj_left_f7_e"+this.id),o=document.getElementById("obj_rotate_left_f7_e"+this.id),p=document.getElementById("obj_translate_right_f7_e"+this.id),q=document.getElementById("obj_border_right_f7_e"+this.id),r=document.getElementById("obj_right_f7_e"+this.id);n.style.width=c+"px",n.style.height=d+"px",o.style.width=c+"px",o.style.height=d+"px",r.style.width=a+"px",r.style.height=b+"px",p.style.width=a+"px",p.style.height=b+"px",q.style.width=a+"px",q.style.height=b+"px",this.style.width=c+a+"px",this.style.height=Math.max(d,b)+"px"}runAnim(){this.handleResize(),this.resetAnimObject(),this.createAnimObject(),this.animation.add({targets:"#obj_translate_right_f7_e"+this.id,left:["100%","0%"],easing:"easeOutSine",duration:this.timeIn/3}).add({targets:"#obj_right_f7_e"+this.id,top:["100%","0%"],easing:"easeOutSine",duration:this.timeIn/4},this.timeIn/4).add({targets:"#obj_left_f7_e"+this.id,easing:"easeOutSine",duration:this.timeIn/4,top:["100%","0%"]},this.timeIn/4).add({targets:"#obj_rotate_left_f7_e"+this.id,rotate:["-180deg","0deg"],easing:"easeInSine",duration:this.timeIn/2},this.timeIn/2).add({targets:"#kintyp_bgr_"+this.id,opacity:[0,1],easing:"linear",duration:this.timeIn},0).add({duration:1,complete:this.handleAnimInEnd.bind(this)}),"yes"===this.hide?this.animation.add({duration:this.timeStay,complete:this.handleAnimStayEnd.bind(this)}).add({targets:"#obj_rotate_left_f7_e"+this.id,rotate:["0deg","-180deg"],easing:"easeInSine",duration:this.timeOut/2}).add({targets:"#obj_left_f7_e"+this.id,rotate:["0deg","-90deg"],easing:"easeOutSine",duration:this.timeOut/6}).add({targets:"#obj_right_f7_e"+this.id,top:["0%","100%"],easing:"easeInSine",duration:this.timeOut/3},"-="+this.timeOut/3).add({targets:"#obj_translate_right_f7_e"+this.id,left:["0%","100%"],easing:"easeInSine",duration:this.timeOut/3}).add({duration:this.wait,complete:this.handleAllAnimEnd.bind(this)}).add({targets:"#kintyp_bgr_"+this.id,opacity:[1,0],easing:"linear",duration:this.timeOut},"-="+this.timeOut).pause():this.animation.add({duration:this.wait,complete:this.handleAllAnimEnd.bind(this)}).pause()}}customElements.define("kintyp-type7-anime",KintypType7Anime);