class KintypType8Anime extends KinTypBase{get main_color(){return this.getAttribute("main_color")||"#ffffff"}static get observedAttributes(){var a=super.observedAttributes;return a.push("main_color"),a}attributeChangedCallback(a,b,c){super.attributeChangedCallback(a,b,c),"main_color"===a&&null!=b&&(document.getElementById("obj_rotate_bottom_f8_e"+this.id).style.backgroundColor=c)}constructor(){super();for(var a,b=``;0<this.topTexts.length;){var c=this.getNode(this.topTexts[0]);a=c.getAttribute("data-id"),a=a?" data-id=\""+a+"\"":"",c.classList.remove("kintyp-top"),b=b+`<div class="`+c.className+` kintyp-top-f8-e`+this.id+`" style="position: relative; white-space:nowrap;`+c.style.cssText+`"`+a+`>`+c.innerHTML+`</div>`,this.removeChild(c)}for(var d=``;0<this.bottomTexts.length;){var e=this.getNode(this.bottomTexts[0]);a=e.getAttribute("data-id"),a=a?" data-id=\""+a+"\"":"",e.classList.remove("kintyp-bottom"),d=d+`<div class="`+e.className+` kintyp-bottom-f8-e`+this.id+`" style="position: relative; white-space:nowrap;`+e.style.cssText+`"`+a+`>`+e.innerHTML+`</div>`,this.removeChild(e)}var f=document.createElement("template");f.innerHTML=`
      `+this.back_panel+`

        <div id="obj_translate_top_f8_e`+this.id+`" style="position: relative; overflow: hidden">
            <div id="obj_top_f8_e`+this.id+`" class="kintyp_flex_centered_c"  style="position: relative;">`+b+`
            </div>
        </div>

        <div id="obj_bottom_perspective_f8_e`+this.id+`">
            <div id="obj_rotate_bottom_f8_e`+this.id+`" style="transform-origin: 0% 0%; position: relative; overflow: hidden; background-color: `+this.main_color+`;">
                <div id="obj_bottom_f8_e`+this.id+`" class="kintyp_flex_centered_c"  style="position: relative;">`+d+`
                </div>
            </div>
        </div>`,this.finishConstruction(f)}handleResize(){this.setSizes();for(var a=0,b=0,c=0,d=document.getElementsByClassName("kintyp-top-f8-e"+this.id),e=0;e<d.length;e++){var f=d[e],g=f.getBoundingClientRect().width,j=f.getBoundingClientRect().height;g>a&&(a=g),b+=j}for(var k=document.getElementsByClassName("kintyp-bottom-f8-e"+this.id),e=0;e<k.length;e++){var l=k[e],g=l.getBoundingClientRect().width,j=l.getBoundingClientRect().height;g>a&&(a=g),c+=j}var m=document.getElementById("obj_top_f8_e"+this.id);m.style.width=a+"px",m.style.height=b+"px";var n=document.getElementById("obj_translate_top_f8_e"+this.id);n.style.width=a+"px",n.style.height=b+"px";var o=document.getElementById("obj_bottom_f8_e"+this.id);o.style.width=a+"px",o.style.height=c+"px";var p=document.getElementById("obj_bottom_perspective_f8_e"+this.id);p.style.perspective=2*a+"px";var q=document.getElementById("obj_rotate_bottom_f8_e"+this.id);q.style.width=a+"px",q.style.height=c+"px",this.style.width=a+"px",this.style.height=b+c+"px",this.style.overflow="visible"}runAnim(){this.handleResize(),this.resetAnimObject(),this.createAnimObject(),this.animation.add({targets:"#obj_rotate_bottom_f8_e"+this.id,opacity:[.5,1],rotateY:["-90deg","-0deg"],easing:"linear",duration:this.timeIn/2}).add({targets:"#obj_top_f8_e"+this.id,top:["100%","0%"],easing:"easeOutSine",duration:this.timeIn/2},this.timeIn/4).add({targets:"#obj_bottom_f8_e"+this.id,left:["-100%","0%"],easing:"spring",duration:this.timeIn/2},this.timeIn/2).add({targets:"#kintyp_bgr_"+this.id,opacity:[0,1],easing:"linear",duration:this.timeIn},0).add({duration:1,complete:this.handleAnimInEnd.bind(this)}),"yes"===this.hide?this.animation.add({duration:this.timeStay,complete:this.handleAnimStayEnd.bind(this)}).add({targets:"#obj_top_f8_e"+this.id,top:["0%","100%"],easing:"easeInSine",duration:this.timeOut/2}).add({targets:"#obj_bottom_f8_e"+this.id,left:["0%","100%"],easing:"easeInSine",duration:this.timeOut/2},"-="+this.timeOut/2).add({targets:"#obj_rotate_bottom_f8_e"+this.id,left:["0%","100%"],width:["100%","0%"],easing:"easeInSine",duration:this.timeOut/2}).add({duration:this.wait,complete:this.handleAllAnimEnd.bind(this)}).add({targets:"#kintyp_bgr_"+this.id,opacity:[1,0],easing:"linear",duration:this.timeOut},"-="+this.timeOut).pause():this.animation.add({duration:this.wait,complete:this.handleAllAnimEnd.bind(this)}).pause()}}customElements.define("kintyp-type8-anime",KintypType8Anime);