class KintypType4Anime extends KinTypBase{get border_size(){return this.getAttribute("border_size")||"1"}get border_color(){return this.getAttribute("border_color")||"#ffffff"}get bgr_color(){return this.getAttribute("bgr_color")||"#ffffff"}get txt_color_below(){return this.getAttribute("txt_color_below")||"#ffffff"}get txt_color_above(){return this.getAttribute("txt_color_above")||"#000000"}get border_radius(){return this.getAttribute("border_radius")||"0"}static get observedAttributes(){var a=super.observedAttributes;return a.push("border_size","border_color","bgr_color","txt_color_below","txt_color_above","border_radius"),a}attributeChangedCallback(a,b,c){if(super.attributeChangedCallback(a,b,c),"border_size"===a&&null!=b)document.getElementById("obj_line_f4_e"+this.id).style.borderBottomWidth=c+"px";else if("border_color"===a&&null!=b)document.getElementById("obj_line_f4_e"+this.id).style.borderBottomColor=c;else if("bgr_color"===a&&null!=b)document.getElementById("obj_anim4_f4_e"+this.id).style.backgroundColor=c;else if("txt_color_below"===a&&null!=b)for(var d=this.getElementsByClassName("kintyp-f4-e"+this.id),e=0;e<d.length;e++)d[e].style.color=c;else if("txt_color_above"===a&&null!=b)for(var d=this.getElementsByClassName("kintyp-f4-above-e"+this.id),e=0;e<d.length;e++)d[e].style.color=c;else"border_radius"===a&&null!=b&&this.handleResize()}constructor(){super();for(var a,b,c=this.getElementsByClassName("kintyp"),d=`<div class="kintyp_flex_centered_c" id="obj_anim3_f4_e`+this.id+`" style="position: absolute; bottom: 0px;">`,e="",f=0;f<c.length;f++){b=this.getNode(c[f]),a=b.getAttribute("data-id"),a=a?" data-id=\""+a+"\"":"";var g=b.className+"";g=g.replace("kintyp",""),e=e+`<div class="`+g+` kintyp-f4-e`+this.id+`" style="white-space:nowrap; color: `+this.txt_color_below+`"`+a+`>`+b.innerHTML+`</div>`}d=d+e+`</div>`,e="";for(var h=this.getElementsByClassName("kintyp"),j=`<div class="kintyp_flex_centered_c" id="obj_anim4_f4_e`+this.id+`" style="position: relative; background-color: `+this.bgr_color+`;">`;0<h.length;){var k=this.getNode(h[0]);a=k.getAttribute("data-id"),a=a?" data-id=\""+a+"\"":"",k.classList.remove("kintyp"),e=e+`<div class="`+k.className+` kintyp-f4-above-e`+this.id+`" style="white-space:nowrap; color: `+this.txt_color_above+`"`+a+`>`+k.innerHTML+`</div>`,this.removeChild(k)}j=j+e+`</div>`;var l=document.createElement("template");l.innerHTML=`
          <div id="obj_below_cont_f4_e`+this.id+`" style="position: absolute">
              <div id="obj_below_mask_f4_e`+this.id+`" style="overflow: hidden; position: absolute; bottom: 0px">`+d+`
              </div>
              <div id="obj_line_f4_e`+this.id+`" style="border-bottom-width: `+this.border_size+`px; border-bottom-style: solid; border-bottom-color: `+this.border_color+`; position: absolute; top: 0px; height: 100%"></div>
          </div>

          <div id="obj_above_cont_f4_e`+this.id+`" style="position: relative;">
              <div id="obj_above_mask_f4_e`+this.id+`" style="overflow: hidden; position: relative">`+j+`
              </div>
          </div>
      
      `,this.finishConstruction(l)}handleResize(){this.setSizes(),this.style.borderRadius=+this.border_radius*this.ratio+"vw";var a=document.getElementById("obj_anim3_f4_e"+this.id);a.style.borderRadius=+this.border_radius*this.ratio+"vw",a=document.getElementById("obj_anim4_f4_e"+this.id),a.style.borderRadius=+this.border_radius*this.ratio+"vw";for(var b,c=0,d=0,e=this.getElementsByClassName("kintyp-f4-e"+this.id),f=0;f<e.length;f++)b=e[f].getBoundingClientRect().width,d+=e[f].getBoundingClientRect().height,b>c&&(c=b);var g=document.getElementById("obj_below_cont_f4_e"+this.id),j=document.getElementById("obj_above_cont_f4_e"+this.id),k=document.getElementById("obj_below_mask_f4_e"+this.id),l=document.getElementById("obj_above_mask_f4_e"+this.id);this.style.width="100%",g.style.width="100%",j.style.width="100%",k.style.width="100%",l.style.width="100%",k.style.width=c+"px",l.style.width=c+"px",g.style.width=c+"px",g.style.height=d+"px",j.style.width=c+"px",j.style.height=d+"px",this.style.width=c+"px",this.style.height=d+4+"px"}runAnim(){this.handleResize(),this.resetAnimObject(),this.createAnimObject(),anime.set("#obj_above_mask_f4_e"+this.id,{height:"0%"}),this.animation.add({targets:"#obj_line_f4_e"+this.id,width:["0%","100%"],easing:"easeInSine",duration:this.timeIn/3}).add({targets:"#obj_line_f4_e"+this.id,top:["0%","-100%"],easing:"easeInSine",duration:this.timeIn/3}).add({targets:"#obj_below_mask_f4_e"+this.id,height:["0%","100%"],easing:"easeInSine",duration:this.timeIn/3},this.timeIn/3).add({targets:"#obj_above_mask_f4_e"+this.id,height:["0%","100%"],easing:"easeOutSine",duration:this.timeIn/3}).add({duration:1,complete:this.handleAnimInEnd.bind(this)}),"yes"===this.hide?this.animation.add({duration:this.timeStay,complete:this.handleAnimStayEnd.bind(this)}).add({targets:"#obj_above_mask_f4_e"+this.id,height:["100%","0%"],easing:"easeInSine",duration:this.timeOut/3}).add({targets:"#obj_below_mask_f4_e"+this.id,height:["100%","0%"],easing:"easeInSine",duration:this.timeOut/3}).add({targets:"#obj_line_f4_e"+this.id,top:["-100%","0%"],easing:"easeInSine",duration:this.timeOut/3},"-="+this.timeOut/3).add({targets:"#obj_line_f4_e"+this.id,left:["0%","105%"],easing:"easeOutSine",duration:this.timeOut/3}).add({duration:this.wait,complete:this.handleAllAnimEnd.bind(this)}).pause():this.animation.add({duration:this.wait,complete:this.handleAllAnimEnd.bind(this)}).pause()}}customElements.define("kintyp-type4-anime",KintypType4Anime);