class KintypType3Anime extends KinTypBase{get bgr_color_top(){return this.getAttribute("bgr_color_top")||"transparent"}get bgr_color_bottom(){return this.getAttribute("bgr_color_bottom")||"transparent"}get border_color_top(){return this.getAttribute("border_color_top")||"transparent"}get border_color_bottom(){return this.getAttribute("border_color_bottom")||"transparent"}static get observedAttributes(){var a=super.observedAttributes;return a.push("bgr_color_top","bgr_color_bottom","border_color_top","border_color_bottom"),a}attributeChangedCallback(a,b,c){super.attributeChangedCallback(a,b,c),"bgr_color_top"===a&&null!=b?document.getElementById("obj_anim3_f3_e"+this.id).style.backgroundColor=c:"bgr_color_bottom"===a&&null!=b?document.getElementById("obj_anim4_f3_e"+this.id).style.backgroundColor=c:"border_color_top"===a&&null!=b?document.getElementById("obj_anim1_f3_e"+this.id).style.borderBottomColor=c:"border_color_bottom"==a&&null!=b&&(document.getElementById("obj_anim2_f3_e"+this.id).style.borderTopColor=c)}constructor(){super();for(var a,b=`<div class="kintyp_flex_centered_c" id="obj_anim3_f3_e`+this.id+`" style="position: absolute; background-color: `+this.bgr_color_top+`; bottom: 0px">`,c="";0<this.topTexts.length;){var d=this.getNode(this.topTexts[0]);a=d.getAttribute("data-id"),a=a?" data-id=\""+a+"\"":"",d.classList.remove("kintyp-top"),c=c+`<div class="`+d.className+` kintyp-top-f3-e`+this.id+`" style="white-space:nowrap;`+d.style.cssText+`"`+a+`>`+d.innerHTML+`</div>`,this.removeChild(d)}b=b+c+`</div>`,c="";for(var e=`<div class="kintyp_flex_centered_c" id="obj_anim4_f3_e`+this.id+`" style="position: relative; background-color: `+this.bgr_color_bottom+`">`;0<this.bottomTexts.length;){var f=this.getNode(this.bottomTexts[0]);a=f.getAttribute("data-id"),a=a?" data-id=\""+a+"\"":"",f.classList.remove("kintyp-bottom"),c=c+`<div class="`+f.className+` kintyp-bottom-f3-e`+this.id+`" style="white-space:nowrap;`+f.style.cssText+`"`+a+`>`+f.innerHTML+`</div>`,this.removeChild(f)}e=e+c+`</div>`;var g=document.createElement("template");g.innerHTML=`
      `+this.back_panel+`
          
          <div id="obj_top_cont_f3_e`+this.id+`" style="position: relative">
              <div id="obj_mask_top_f3_e`+this.id+`" style="overflow: hidden; position: absolute; bottom: 0px">`+b+`
              </div>
              <div id="obj_anim1_f3_e`+this.id+`" style="box-sizing: content-box; border-bottom-width: 2px; border-bottom-style:solid; border-bottom-color: `+this.border_color_top+`; position: absolute; top: 0px; width: 100%"></div>
          </div>

          <div id="obj_bottom_cont_f3_e`+this.id+`" style="position: relative">
              <div id="obj_mask_bottom_f3_e`+this.id+`" style="overflow: hidden; position: relative;">`+e+`
              </div>
              <div id="obj_anim2_f3_e`+this.id+`" style="width: 100%; border-top-width: 2px; border-top-style:solid; border-top-color: `+this.border_color_bottom+`; position: absolute; top: 0px"></div>            
          </div>
      
      `,this.finishConstruction(g)}handleResize(){this.setSizes();var a=document.getElementById("obj_mask_top_f3_e"+this.id),b=document.getElementById("obj_mask_bottom_f3_e"+this.id),c=document.getElementById("obj_bottom_cont_f3_e"+this.id),d=document.getElementById("obj_top_cont_f3_e"+this.id),e=document.getElementById("obj_anim1_f3_e"+this.id),f=document.getElementById("obj_anim3_f3_e"+this.id);this.style.width="100%",a.style.width="100%",d.style.width="100%",b.style.width="100%",c.style.width="100%",f.style.width="100%";for(var g,h=0,j=0,k=0,l=document.getElementsByClassName("kintyp-top-f3-e"+this.id),m=document.getElementsByClassName("kintyp-bottom-f3-e"+this.id),n=0;n<l.length;n++)g=l[n].getBoundingClientRect().width,j+=l[n].getBoundingClientRect().height,g>h&&(h=g);for(var g,n=0;n<m.length;n++)g=m[n].getBoundingClientRect().width,g>h&&(h=g),k+=m[n].getBoundingClientRect().height;a.style.width=h+"px",a.style.height="100%",b.style.width=h+"px",c.style.width=h+"px",c.style.height=k+"px",d.style.width=h+"px",d.style.height=j+"px",e.style.height=j+"px",e.style.width=h+"px",f.style.width=h+"px",this.style.width=h+"px",this.style.height=j+k+2+"px"}runAnim(){this.handleResize(),this.resetAnimObject(),this.createAnimObject(),this.animation.add({targets:"#obj_anim1_f3_e"+this.id+", #obj_anim2_f3_e"+this.id,width:["0%","100%"],easing:"easeInSine",duration:this.timeIn/2}).add({targets:"#obj_anim1_f3_e"+this.id,top:["0%","-100%"],easing:"linear",duration:this.timeIn/2}).add({targets:"#obj_anim2_f3_e"+this.id,top:["0%","100%"],easing:"linear",duration:this.timeIn/2},this.timeIn/2).add({targets:"#kintyp_bgr_"+this.id,opacity:[0,1],easing:"linear",duration:this.timeIn},0).add({targets:"#obj_mask_top_f3_e"+this.id,height:["0%","100%"],easing:"linear",duration:this.timeIn/2},this.timeIn/2).add({targets:"#obj_mask_bottom_f3_e"+this.id,height:["0%","100%"],easing:"linear",duration:this.timeIn/2},this.timeIn/2).add({duration:1,complete:this.handleAnimInEnd.bind(this)}),"yes"===this.hide?this.animation.add({duration:this.timeStay,complete:this.handleAnimStayEnd.bind(this)}).add({targets:"#obj_anim3_f3_e"+this.id,bottom:["0%","110%"],easing:"easeOutSine",duration:this.timeOut/2}).add({targets:"#obj_anim4_f3_e"+this.id,top:["0%","110%"],easing:"easeOutSine",duration:this.timeOut/2},"-="+this.timeOut/2).add({targets:"#obj_anim1_f3_e"+this.id,left:["0%","110%"],easing:"easeInOutSine",duration:this.timeOut/2}).add({targets:"#obj_anim2_f3_e"+this.id,left:["0%","-110%"],easing:"easeInOutSine",duration:this.timeOut/2},"-="+this.timeOut/2).add({duration:this.wait,complete:this.handleAllAnimEnd.bind(this)}).add({targets:"#kintyp_bgr_"+this.id,opacity:[1,0],easing:"linear",duration:this.timeOut},"-="+this.timeOut).pause():this.animation.add({duration:this.wait,complete:this.handleAllAnimEnd.bind(this)}).pause()}}customElements.define("kintyp-type3-anime",KintypType3Anime);